# Generated by Django 3.2.6 on 2022-09-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfg', models.DateTimeField()),
                ('name', models.CharField(max_length=20)),
                ('quntity', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('manafucture', models.CharField(max_length=20)),
                ('exp_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreKipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.BigIntegerField()),
                ('nid', models.CharField(max_length=50)),
                ('Salary', models.BigIntegerField()),
                ('join_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.BigIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('store_kiper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.storekipper')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('quntity', models.BigIntegerField()),
                ('waranty', models.BigIntegerField()),
                ('purchase_date', models.DateTimeField()),
                ('sub_total', models.BigIntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine')),
            ],
        ),
    ]
